export const VALID_PACKAGE_NAMES = [
  'react',
  'react-dom',
  'lodash',
  'vite',
  'next',
  'express',
  'pkg_name',
  'pkg.name',
  'pkg~name',
  'a',
  'a1',
  '1pkg',
  'my-package',
  'my.package',
  'my_package',
  '@types/node',
  '@types/react',
  '@my-org/utils',
  '@scope/pkg',
  '@scope/pkg.name',
  '@scope/pkg_name',
  '@scope/pkg~name',
  '@scope123/pkg-123',
] as const;

export const INVALID_PACKAGE_NAMES = [
  '',
  ' ',
  'React',
  'MyPackage',
  'HELLO',
  '@Scope/pkg',
  '@scope',
  '@scope/',
  '@/pkg',
  '/pkg',
  '.pkg',
  '-pkg',
  '~pkg',
  'pkg space',
  'pkg/name',
  '@scope/pkg/name',
  '@scope//pkg',
  '@@scope/pkg',
  'my*package',
  'my?package',
  'my#package',
  'my\\package',
  'my:package',
  'my%package',
] as const;
