name: autofix.ci

permissions:
  contents: read

on:
  pull_request:

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/setup
      - run: |
          pnpm lint:fix
          pnpm deps:sync
          pnpm sync
          pnpm gen
          pnpm fmt

      - run: |
          if ! git diff --quiet; then
            echo "────────────────────────────────────────"
            echo "The following files are not up to date"
            echo "────────────────────────────────────────"
            echo ""
            git diff --name-only \
            | sed 's/^/  - /'
            echo ""
            echo "────────────────────────────────────────"
            echo "Actual diff:"
            echo "────────────────────────────────────────"
            echo ""
            git --no-pager diff
          else
            echo "No changes detected. All generated files are up to date."
          fi

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1
