name: CI

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/setup
      - run: |
          pnpm build
          pnpm checks
          pnpm lint
          pnpm fmt:check
          pnpm typecheck

  tests:
    runs-on: ubuntu-latest
    name: Node.js ${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [22, 24, 26]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          pnpm build
          pnpm test
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        if: matrix.node-version == 22
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  typedoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/setup
      - run: |
          pnpm build
          pnpm build:docs

  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/setup
      - run: |
          pnpm build
      - name: Release Preview
        run: pnpm dlx pkg-pr-new publish './packages/**' --packageManager=npm,pnpm,yarn,bun
