name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  pages: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_CONFIG_PROVENANCE: true
    outputs:
      published: ${{ steps.changesets.outputs.published }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - run: |
          pnpm build
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run changeset:version
          publish: pnpm run changeset:publish

  deploy:
    needs: publish
    if: github.ref == 'refs/heads/main' && (needs.publish.outputs.published == 'true' || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/setup
      - name: Build documentation
        run: |
          pnpm build
          pnpm build:docs
      - name: Run tests
        run: pnpm test
      - name: Copy content files to docs
        run: |
          mkdir -p docs

          find packages -type d -name coverage | while read dir; do
            if [ -d "$dir" ]; then
              pkg=$(basename "$(dirname "$dir")")
              mkdir -p "docs/coverage/$pkg"
              cp -r "$dir/"* "docs/coverage/$pkg/"
            fi
          done

          cp google88133773e6f7fb4f.html docs/google88133773e6f7fb4f.html
          cp exports.json docs/exports.json
      - name: Configure Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6
      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: ./docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
