name: Tests
permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/**'
      - 'tests/**'
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      src_changed: ${{ steps.check.outputs.any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for src changes
        id: check
        uses: tj-actions/changed-files@v46
        with:
          files: src/**

  run_tests:
    name: Run yarn test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test --coverage

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  jsr_check:
    name: JSR Publish Check (Dry Run)
    needs: [run_tests, detect_changes]
    runs-on: ubuntu-latest
    if: needs.detect_changes.outputs.src_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Dry-run JSR publish
        run: npx jsr publish --dry-run

  sheriff:
    name: Check PR title
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Validate PR title
        uses: teneplaysofficial/sheriff@v3
